apiVersion: v1
kind: ConfigMap
metadata:
      name: todo-config
      namespace: default
data:
  PORT: "3001"
  DB_HOST: myapp.cfym6wc6iyzn.ap-south-1.rds.amazonaws.com
  DB_NAME: todo_app
  DB_PORT: "3306"
