apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
  labels:
    app: todo-auth
spec:
  replicas: 2
  selector:
    matchLabels:
      app: todo-auth
  template:
    metadata:
      labels:
        app: todo-auth
    spec:
      containers:
        - name: auth
          image: raichu08/todo-auth:latest
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: todo-config
                  key: PORT
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: todo-config
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: todo-config
                  key: DB_PORT
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: todo-config
                  key: DB_NAME
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: todo-secret
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: todo-secret
                  key: DB_PASSWORD
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: todo-secret
                  key: JWT_SECRET
